import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const tools = [
  // ===== AI视频制作 (10�? =====
  {
    id: 'pika-labs',
    name: 'Pika Labs',
    slug: 'pika-labs',
    description: 'AI video generation platform that transforms text and images into stunning videos with cinematic quality',
    websiteUrl: 'https://pika.art/',
    logoUrl: '/images/tools/pika.svg',
    category: 'AI Video',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 8,
    pros: JSON.stringify(['Text-to-video with cinematic quality', 'Image-to-video animation', 'Video editing with AI', 'Fast generation speed']),
    cons: JSON.stringify(['Limited free credits per day', 'Watermark on free tier', 'Complex scenes may need refinement']),
  },
  {
    id: 'invideo-ai',
    name: 'InVideo AI',
    slug: 'invideo-ai',
    description: 'AI-powered video creation platform that turns text prompts into professional videos with stock footage and voiceovers',
    websiteUrl: 'https://invideo.io/',
    logoUrl: '/images/tools/invideo.svg',
    category: 'AI Video',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 20,
    pros: JSON.stringify(['Turns text prompts into complete videos', 'Massive stock media library', 'AI voiceover generation', 'Multiple video styles and templates']),
    cons: JSON.stringify(['Stock footage may feel generic', 'Limited customization for complex projects', 'Export quality depends on plan']),
  },
  {
    id: 'fliki-ai',
    name: 'Fliki AI',
    slug: 'fliki-ai',
    description: 'AI video and voice generation tool that converts blog posts and scripts into engaging videos with realistic voiceovers',
    websiteUrl: 'https://fliki.ai/',
    logoUrl: '/images/tools/fliki.svg',
    category: 'AI Video',
    rating: 4.4,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 24,
    pros: JSON.stringify(['Converts text to video automatically', '750+ AI voices in 75 languages', 'Blog-to-video feature', 'Social media optimization']),
    cons: JSON.stringify(['Limited video editing capabilities', 'Some voices sound robotic', 'Free tier has watermarks']),
  },
  {
    id: 'loom-ai',
    name: 'Loom AI',
    slug: 'loom-ai',
    description: 'AI-powered screen recording and video messaging platform with automatic transcriptions, summaries, and editing',
    websiteUrl: 'https://www.loom.com/',
    logoUrl: '/images/tools/loom.svg',
    category: 'AI Video',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 12,
    pros: JSON.stringify(['Automatic video summaries', 'AI-generated titles and descriptions', 'Instant transcriptions', 'Easy sharing and collaboration']),
    cons: JSON.stringify(['Limited recording time on free plan', 'AI features require paid plan', 'Basic editing only']),
  },
  {
    id: 'veo2-google',
    name: 'Google Veo 2',
    slug: 'veo2-google',
    description: 'Google\'s advanced AI video generation model capable of creating high-quality, photorealistic videos from text prompts',
    websiteUrl: 'https://deepmind.google/technologies/veo/',
    logoUrl: '/images/tools/veo.svg',
    category: 'AI Video',
    rating: 4.8,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 30,
    pros: JSON.stringify(['Photorealistic video quality', 'Long video generation (up to 8 minutes)', 'Cinematic camera movements', 'Available via Google AI Studio']),
    cons: JSON.stringify(['Limited availability', 'High computational cost', 'Complex prompts needed for best results']),
  },
  {
    id: 'hailuo-mini-max',
    name: 'Hailuo AI (MiniMax)',
    slug: 'hailuo-mini-max',
    description: 'Chinese AI video generation platform known for realistic human movement and cinematic quality outputs',
    websiteUrl: 'https://www.hailuoai.com/',
    logoUrl: '/images/tools/hailuo.svg',
    category: 'AI Video',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 15,
    pros: JSON.stringify(['Realistic human movement', 'Cinematic quality outputs', 'Fast generation speed', 'Growing prompt library']),
    cons: JSON.stringify(['Chinese interface (limited English)', 'Limited international availability', 'Community still growing']),
  },
  {
    id: 'vidu-ai',
    name: 'Vidu AI',
    slug: 'vidu-ai',
    description: 'AI video generation tool specializing in character animation and consistent character design across scenes',
    websiteUrl: 'https://www.vidu.studio/',
    logoUrl: '/images/tools/vidu.svg',
    category: 'AI Video',
    rating: 4.3,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 12,
    pros: JSON.stringify(['Character consistency across scenes', 'Storyboard generation', 'Multiple video styles', 'Character animation focus']),
    cons: JSON.stringify(['Limited scene complexity', 'Shorter video durations', 'Learning curve for advanced features']),
  },
  {
    id: 'clipchamp-microsoft',
    name: 'Microsoft Clipchamp AI',
    slug: 'clipchamp-microsoft',
    description: 'Microsoft\'s AI-enhanced video editor with automatic editing, captions, and professional templates',
    websiteUrl: 'https://clipchamp.com/',
    logoUrl: '/images/tools/clipchamp.svg',
    category: 'AI Video',
    rating: 4.4,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 11.99,
    pros: JSON.stringify(['Built into Windows 11', 'AI auto-editing', 'Text-to-speech voiceovers', 'Extensive template library']),
    cons: JSON.stringify(['Basic features only on free tier', 'Watermark on exports', 'Limited advanced editing']),
  },
  {
    id: 'descript-overdub',
    name: 'Descript Overdub',
    slug: 'descript-overdub',
    description: 'AI voice cloning and editing tool that lets you edit audio by editing text, with realistic voice cloning capabilities',
    websiteUrl: 'https://www.descript.com/overdub',
    logoUrl: '/images/tools/descript.svg',
    category: 'AI Video',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 24,
    pros: JSON.stringify(['Edit audio by editing text', 'Realistic voice cloning', 'AI-generated filler word removal', 'Transcription accuracy']),
    cons: JSON.stringify(['Voice cloning requires training', 'Ethical concerns with voice cloning', 'Limited free tier']),
  },
  {
    id: 'capcut-ai',
    name: 'CapCut AI',
    slug: 'capcut-ai',
    description: 'TikTok\'s AI-powered video editor with smart cutouts, auto captions, templates, and viral content features',
    websiteUrl: 'https://www.capcut.com/',
    logoUrl: '/images/tools/capcut.svg',
    category: 'AI Video',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 9.99,
    pros: JSON.stringify(['Free with most features included', 'Trending templates and effects', 'AI auto-captions', 'Smart cutout and background removal']),
    cons: JSON.stringify(['Pro features require subscription', 'Watermark on some exports', 'Desktop version less polished than mobile']),
  },

  // ===== AI图像处理 (12�? =====
  {
    id: 'flux-ai',
    name: 'Flux AI',
    slug: 'flux-ai',
    description: 'State-of-the-art open-weight AI image generation model by Black Forest Labs with exceptional prompt understanding',
    websiteUrl: 'https://fluxai.ai/',
    logoUrl: '/images/tools/flux.svg',
    category: 'AI Image',
    rating: 4.9,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 10,
    pros: JSON.stringify(['Exceptional prompt understanding', 'Open-weight model', 'Photorealistic outputs', 'Handles complex compositions']),
    cons: JSON.stringify(['Requires GPU for local running', 'Free tier has limits', 'Commercial use requires license']),
  },
  {
    id: 'ideogram-ai',
    name: 'Ideogram AI',
    slug: 'ideogram-ai',
    description: 'AI image generator that excels at creating designs with accurate, readable text integration',
    websiteUrl: 'https://ideogram.ai/',
    logoUrl: '/images/tools/ideogram.svg',
    category: 'AI Image',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 10,
    pros: JSON.stringify(['Best-in-class text rendering', 'Design-focused features', 'Logo and poster generation', 'Creative community']),
    cons: JSON.stringify(['Limited realism compared to competitors', 'Free tier has daily limits', 'Style variety could be broader']),
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    slug: 'kling-ai',
    description: 'Advanced AI video and image generation platform by Kuaishou with photorealistic quality and human movement',
    websiteUrl: 'https://klingai.com/',
    logoUrl: '/images/tools/kling.svg',
    category: 'AI Image',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 15,
    pros: JSON.stringify(['Photorealistic image quality', 'Excellent human figure generation', 'Video and image in one platform', 'Fast generation speed']),
    cons: JSON.stringify(['Limited international availability', 'Chinese origin may concern some users', 'Pricing still evolving']),
  },
  {
    id: 'recraft-ai',
    name: 'Recraft AI',
    slug: 'recraft-ai',
    description: 'AI design tool that generates consistent brand assets, vector graphics, and illustrations with style control',
    websiteUrl: 'https://www.recraft.ai/',
    logoUrl: '/images/tools/recraft.svg',
    category: 'AI Image',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 16,
    pros: JSON.stringify(['Vector graphics generation', 'Brand style consistency', 'Illustration creation', 'Professional design output']),
    cons: JSON.stringify(['Steeper learning curve', 'Limited photorealism', 'Subscription required for full features']),
  },
  {
    id: 'canva-magic-studio',
    name: 'Canva Magic Studio',
    slug: 'canva-magic-studio',
    description: 'Canva\'s AI-powered design suite with Magic Write, Magic Media, Brand Kit AI, and automated design tools',
    websiteUrl: 'https://www.canva.com/magic-studio/',
    logoUrl: '/images/tools/canva.svg',
    category: 'AI Image',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 12.99,
    pros: JSON.stringify(['All-in-one design platform', 'Magic Write AI text generation', 'Magic Edit for photo editing', 'Huge template library']),
    cons: JSON.stringify(['Some AI features require Pro', 'Design quality varies', 'Limited advanced photo editing']),
  },
  {
    id: 'comfyui',
    name: 'ComfyUI',
    slug: 'comfyui',
    description: 'Node-based UI for Stable Diffusion that enables advanced AI image generation workflows with custom pipelines',
    websiteUrl: 'https://www.comfy.org/',
    logoUrl: '/images/tools/comfyui.svg',
    category: 'AI Image',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREE',
    priceMonthly: 0,
    pros: JSON.stringify(['Completely free and open-source', 'Advanced workflow customization', 'Community-driven development', 'Powerful for experts']),
    cons: JSON.stringify(['Steep learning curve', 'Requires technical knowledge', 'No official cloud hosting']),
  },
  {
    id: 'leonardo-ai-v2',
    name: 'Leonardo AI v2',
    slug: 'leonardo-ai-v2',
    description: 'AI art generation platform with trained custom models, real-time canvas, and game asset creation tools',
    websiteUrl: 'https://leonardo.ai/',
    logoUrl: '/images/tools/leonardo.svg',
    category: 'AI Image',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 10,
    pros: JSON.stringify(['Custom model training', 'Real-time canvas feature', 'Game asset generation', 'High-quality artistic outputs']),
    cons: JSON.stringify(['Token system limits free usage', 'Can be slow during peak hours', 'Mobile app limited']),
  },
  {
    id: 'playground-ai',
    name: 'Playground AI',
    slug: 'playground-ai',
    description: 'AI image generation platform with canvas editing, style filters, and professional design tools',
    websiteUrl: 'https://playgroundai.com/',
    logoUrl: '/images/tools/playground.svg',
    category: 'AI Image',
    rating: 4.4,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 15,
    pros: JSON.stringify(['Professional canvas editor', 'Multiple AI models available', 'Style filter library', 'Commercial usage rights']),
    cons: JSON.stringify(['Interface can be overwhelming', 'Generation speed varies', 'Free tier limited to 50 images/day']),
  },
  {
    id: 'photoshop-ai',
    name: 'Adobe Photoshop AI (Firefly)',
    slug: 'photoshop-ai-firefly',
    description: 'Adobe\'s AI-powered image editor with Generative Fill, Expand, and other Firefly-powered features',
    websiteUrl: 'https://www.adobe.com/products/photoshop/ai.html',
    logoUrl: '/images/tools/photoshop.svg',
    category: 'AI Image',
    rating: 4.8,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 22.99,
    pros: JSON.stringify(['Industry-standard editor', 'Generative Fill and Expand', 'Seamless AI integration', 'Commercial-safe AI outputs']),
    cons: JSON.stringify(['Expensive subscription', 'Learning curve for beginners', 'AI features require Creative Cloud']),
  },
  {
    id: 'stability-ai-image',
    name: 'Stability AI Image Suite',
    slug: 'stability-ai-image',
    description: 'Open-source AI image generation platform offering Stable Diffusion models, APIs, and enterprise solutions',
    websiteUrl: 'https://stability.ai/',
    logoUrl: '/images/tools/stability.svg',
    category: 'AI Image',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 10,
    pros: JSON.stringify(['Open-source models', 'API access for developers', 'Enterprise solutions', 'Multiple model variants']),
    cons: JSON.stringify(['Requires technical setup for self-hosting', 'API costs can add up', 'Documentation can be confusing']),
  },
  {
    id: 'krea-ai',
    name: 'Krea AI',
    slug: 'krea-ai',
    description: 'Real-time AI image generation tool with live canvas that responds to prompts and sketches instantly',
    websiteUrl: 'https://www.krea.ai/',
    logoUrl: '/images/tools/krea.svg',
    category: 'AI Image',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 8,
    pros: JSON.stringify(['Real-time generation', 'Interactive canvas', 'Pattern and logo creation', 'Fast iterative design']),
    cons: JSON.stringify(['Limited resolution on free tier', 'Style variety could be broader', 'Requires stable internet connection']),
  },
  {
    id: 'tensor-art',
    name: 'Tensor.art',
    slug: 'tensor-art',
    description: 'AI art platform with thousands of community-trained models, anime focus, and free daily generations',
    websiteUrl: 'https://tensor.art/',
    logoUrl: '/images/tools/tensor.svg',
    category: 'AI Image',
    rating: 4.3,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 5,
    pros: JSON.stringify(['Thousands of community models', 'Strong anime and art styles', 'Free daily generations', 'Model sharing community']),
    cons: JSON.stringify(['Quality varies by model', 'Western art styles less developed', 'Interface can be cluttered']),
  },

  // ===== AI写作工具 (8�? =====
  {
    id: 'claude-writing',
    name: 'Claude (Writing Assistant)',
    slug: 'claude-writing',
    description: 'Anthropic\'s AI assistant excelling at long-form writing, editing, and content analysis with exceptional context handling',
    websiteUrl: 'https://claude.ai/',
    logoUrl: '/images/tools/claude.svg',
    category: 'AI Writing',
    rating: 4.9,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 20,
    pros: JSON.stringify(['Superior long-form writing', '200K context window', 'Excellent editing capabilities', 'Natural, human-like tone']),
    cons: JSON.stringify(['No image generation', 'Limited free tier', 'Slower than some competitors']),
  },
  {
    id: 'chatgpt-writing',
    name: 'ChatGPT (Writing Assistant)',
    slug: 'chatgpt-writing',
    description: 'OpenAI\'s versatile AI assistant for writing, brainstorming, research, and content creation across all formats',
    websiteUrl: 'https://chatgpt.com/',
    logoUrl: '/images/tools/chatgpt.svg',
    category: 'AI Writing',
    rating: 4.8,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 20,
    pros: JSON.stringify(['Versatile across all writing types', 'Real-time web search (Pro)', 'Code generation', 'Multimodal capabilities']),
    cons: JSON.stringify(['Can hallucinate facts', 'Generic writing style at times', 'Usage limits on free tier']),
  },
  {
    id: 'gemini-writing',
    name: 'Google Gemini (Writing Assistant)',
    slug: 'gemini-writing',
    description: 'Google\'s multimodal AI assistant with deep integration into Google Workspace and exceptional research capabilities',
    websiteUrl: 'https://gemini.google.com/',
    logoUrl: '/images/tools/gemini.svg',
    category: 'AI Writing',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 20,
    pros: JSON.stringify(['Deep Google Workspace integration', 'Real-time web search', 'Multimodal input handling', 'Free tier generous']),
    cons: JSON.stringify(['Writing style can be generic', 'Less nuanced than Claude', 'Google ecosystem dependency']),
  },
  {
    id: 'grammarly-ai',
    name: 'Grammarly AI',
    slug: 'grammarly-ai',
    description: 'AI-powered writing assistant with grammar checking, tone detection, style suggestions, and clarity improvements',
    websiteUrl: 'https://www.grammarly.com/',
    logoUrl: '/images/tools/grammarly.svg',
    category: 'AI Writing',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 12,
    pros: JSON.stringify(['Excellent grammar checking', 'Tone detection', 'Works everywhere online', 'Style and clarity suggestions']),
    cons: JSON.stringify(['Can be overly prescriptive', 'Premium required for advanced features', 'May suggest unnecessary changes']),
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    slug: 'quillbot',
    description: 'AI paraphrasing and writing tool with multiple modes, citation generator, and grammar checker',
    websiteUrl: 'https://quillbot.com/',
    logoUrl: '/images/tools/quillbot.svg',
    category: 'AI Writing',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 9.95,
    pros: JSON.stringify(['Multiple paraphrasing modes', 'Citation generator', 'Summarizer tool', 'Plagiarism checker']),
    cons: JSON.stringify(['Paraphrasing can change meaning', 'Limited free usage', 'Interface is basic']),
  },
  {
    id: 'hemingway-editor',
    name: 'Hemingway Editor AI',
    slug: 'hemingway-editor',
    description: 'AI-enhanced writing editor that highlights complex sentences, adverbs, passive voice, and suggests improvements',
    websiteUrl: 'https://hemingwayapp.com/',
    logoUrl: '/images/tools/hemingway.svg',
    category: 'AI Writing',
    rating: 4.4,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 19.99,
    pros: JSON.stringify(['Clear readability scoring', 'Highlights complex sentences', 'Passive voice detection', 'Suggests simpler alternatives']),
    cons: JSON.stringify(['Can be overly simplistic', 'No cloud saving', 'Desktop app only']),
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    slug: 'wordtune',
    description: 'AI writing companion that rewrites sentences for clarity, tone, and style with contextual suggestions',
    websiteUrl: 'https://www.wordtune.com/',
    logoUrl: '/images/tools/wordtune.svg',
    category: 'AI Writing',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 9.99,
    pros: JSON.stringify(['Contextual rewriting suggestions', 'Tone adjustment', 'Integration with major platforms', 'Quick sentence improvements']),
    cons: JSON.stringify(['Limited free daily rewrites', 'Can suggest awkward phrasing', 'No long-form generation']),
  },
  {
    id: 'frase-io',
    name: 'Frase.io',
    slug: 'frase-io',
    description: 'AI content optimization platform for SEO writing with research, outline generation, and content scoring',
    websiteUrl: 'https://www.frase.io/',
    logoUrl: '/images/tools/frase.svg',
    category: 'AI Writing',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 14.99,
    pros: JSON.stringify(['SEO-optimized content creation', 'Competitor research', 'AI outline generation', 'Content scoring']),
    cons: JSON.stringify(['Content can feel generic', 'Learning curve for SEO features', 'Pricing for teams is high']),
  },

  // ===== AI音频工具 (6�? =====
  {
    id: 'suno-v4',
    name: 'Suno v4',
    slug: 'suno-v4',
    description: 'AI music generation platform that creates complete songs with vocals, instruments, and professional production quality',
    websiteUrl: 'https://suno.com/',
    logoUrl: '/images/tools/suno.svg',
    category: 'AI Audio',
    rating: 4.8,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 10,
    pros: JSON.stringify(['Creates complete songs with vocals', 'Multiple genres and styles', 'Professional production quality', 'Easy to use interface']),
    cons: JSON.stringify(['Vocal quality varies', 'Limited control over specific elements', 'Free tier has daily limits']),
  },
  {
    id: 'elevenlabs-v2',
    name: 'ElevenLabs v2',
    slug: 'elevenlabs-v2',
    description: 'Leading AI voice synthesis platform with voice cloning, multilingual support, and emotional expression control',
    websiteUrl: 'https://elevenlabs.io/',
    logoUrl: '/images/tools/elevenlabs.svg',
    category: 'AI Audio',
    rating: 4.9,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 5,
    pros: JSON.stringify(['Most realistic AI voices', 'Voice cloning technology', 'Multilingual support', 'Emotional expression control']),
    cons: JSON.stringify(['Ethical concerns with voice cloning', 'Free tier limited', 'Pronunciation can be inconsistent']),
  },
  {
    id: 'murf-ai',
    name: 'Murf AI',
    slug: 'murf-ai',
    description: 'AI voice generator with studio-quality voices, video synchronization, and team collaboration features',
    websiteUrl: 'https://murf.ai/',
    logoUrl: '/images/tools/murf.svg',
    category: 'AI Audio',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 19,
    pros: JSON.stringify(['Studio-quality voice generation', 'Video synchronization', 'Team collaboration', '120+ voices in 20+ languages']),
    cons: JSON.stringify(['More expensive than competitors', 'Some voices sound robotic', 'Free tier very limited']),
  },
  {
    id: 'udio-ai',
    name: 'Udio AI',
    slug: 'udio-ai',
    description: 'AI music creation platform with high-fidelity audio, lyrical content generation, and professional mixing',
    websiteUrl: 'https://www.udio.com/',
    logoUrl: '/images/tools/udio.svg',
    category: 'AI Audio',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 10,
    pros: JSON.stringify(['High-fidelity audio output', 'AI-generated lyrics', 'Professional mixing', 'Song extension and remixing']),
    cons: JSON.stringify(['Limited free generations', 'Some genres sound better than others', 'Copyright concerns for commercial use']),
  },
  {
    id: 'podcastle-ai',
    name: 'Podcastle AI',
    slug: 'podcastle-ai',
    description: 'AI-powered podcast creation platform with voice cloning, editing, transcription, and audio enhancement',
    websiteUrl: 'https://podcastle.ai/',
    logoUrl: '/images/tools/podcastle.svg',
    category: 'AI Audio',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 11.99,
    pros: JSON.stringify(['All-in-one podcast platform', 'AI voice cloning', 'Magic Dust audio enhancement', 'Automatic transcription']),
    cons: JSON.stringify(['Limited free features', 'Voice cloning accuracy varies', 'Web-based only']),
  },
  {
    id: 'adobe-podcast',
    name: 'Adobe Podcast',
    slug: 'adobe-podcast',
    description: 'Adobe\'s AI-powered podcast platform with recording, editing, transcription, and AI voice enhancement',
    websiteUrl: 'https://podcast.adobe.com/',
    logoUrl: '/images/tools/adobe-podcast.svg',
    category: 'AI Audio',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 11.99,
    pros: JSON.stringify(['Studio-quality recording', 'AI voice enhancement', 'Automatic transcription', 'Integration with Adobe ecosystem']),
    cons: JSON.stringify(['Limited free tier', 'Requires Adobe account', 'Advanced features need Premium']),
  },

  // ===== AI编程工具 (6�? =====
  {
    id: 'bolt-new',
    name: 'Bolt.new',
    slug: 'bolt-new',
    description: 'AI-powered full-stack development platform that builds complete web applications from natural language prompts',
    websiteUrl: 'https://bolt.new/',
    logoUrl: '/images/tools/bolt.svg',
    category: 'AI Coding',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 20,
    pros: JSON.stringify(['Builds complete web apps from prompts', 'Full-stack development', 'Real-time preview', 'Multiple framework support']),
    cons: JSON.stringify(['Complex apps may need manual coding', 'Free tier limited', 'Still evolving technology']),
  },
  {
    id: 'v0-dev',
    name: 'v0 by Vercel',
    slug: 'v0-dev',
    description: 'AI-powered UI generation tool by Vercel that creates React components and full pages from text descriptions',
    websiteUrl: 'https://v0.dev/',
    logoUrl: '/images/tools/v0.svg',
    category: 'AI Coding',
    rating: 4.8,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 20,
    pros: JSON.stringify(['Generates React components instantly', 'Shadcn/ui integration', 'Production-ready code', 'Vercel ecosystem integration']),
    cons: JSON.stringify(['Limited to React/Next.js', 'Complex layouts may need tweaking', 'Free tier has limits']),
  },
  {
    id: 'windsurf-ide',
    name: 'Windsurf IDE',
    slug: 'windsurf-ide',
    description: 'AI-native IDE with deep codebase understanding, multi-file editing, and intelligent code completion',
    websiteUrl: 'https://codeium.com/windsurf',
    logoUrl: '/images/tools/windsurf.svg',
    category: 'AI Coding',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 15,
    pros: JSON.stringify(['Deep codebase understanding', 'Multi-file AI editing', 'Intelligent code completion', 'VS Code compatible']),
    cons: JSON.stringify(['Still in beta', 'Resource intensive', 'Limited language support initially']),
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    slug: 'replit-agent',
    description: 'AI coding agent that plans, writes, and debugs code in an interactive development environment',
    websiteUrl: 'https://replit.com/ai',
    logoUrl: '/images/tools/replit.svg',
    category: 'AI Coding',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 25,
    pros: JSON.stringify(['Interactive AI coding agent', 'Plans before coding', 'Debugging assistance', 'Cloud-based development']),
    cons: JSON.stringify(['Requires subscription', 'Internet dependency', 'Complex projects need guidance']),
  },
  {
    id: 'github-copilot-workspace',
    name: 'GitHub Copilot Workspace',
    slug: 'github-copilot-workspace',
    description: 'GitHub\'s AI-powered development environment with workspace-wide context, natural language task planning, and automated coding',
    websiteUrl: 'https://github.com/features/copilot-workspace',
    logoUrl: '/images/tools/copilot.svg',
    category: 'AI Coding',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 10,
    pros: JSON.stringify(['Workspace-wide context', 'Natural language task planning', 'GitHub integration', 'Automated coding from specs']),
    cons: JSON.stringify(['Requires GitHub subscription', 'Still evolving', 'Complex tasks need oversight']),
  },
  {
    id: 'aider-ai',
    name: 'Aider',
    slug: 'aider-ai',
    description: 'AI pair programming tool for the command line that edits code directly in your local repository',
    websiteUrl: 'https://aider.chat/',
    logoUrl: '/images/tools/aider.svg',
    category: 'AI Coding',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'FREE',
    priceMonthly: 0,
    pros: JSON.stringify(['Command-line interface', 'Edits code in local repo', 'Multiple LLM support', 'Free and open-source']),
    cons: JSON.stringify(['Requires technical setup', 'No GUI', 'Depends on external LLM APIs']),
  },

  // ===== AI办公与效率工�?(8�? =====
  {
    id: 'gamma-ai-v2',
    name: 'Gamma AI v2',
    slug: 'gamma-ai-v2',
    description: 'AI-powered presentation and document creation platform with beautiful templates and real-time collaboration',
    websiteUrl: 'https://gamma.app/',
    logoUrl: '/images/tools/gamma.svg',
    category: 'AI Productivity',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 10,
    pros: JSON.stringify(['Beautiful presentation templates', 'AI content generation', 'Real-time collaboration', 'Export to multiple formats']),
    cons: JSON.stringify(['Limited customization on free tier', 'Some templates feel generic', 'Animation options limited']),
  },
  {
    id: 'beautiful-ai',
    name: 'Beautiful.ai',
    slug: 'beautiful-ai',
    description: 'Smart presentation software with AI design assistance, team collaboration, and analytics',
    websiteUrl: 'https://www.beautiful.ai/',
    logoUrl: '/images/tools/beautiful.svg',
    category: 'AI Productivity',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 12,
    pros: JSON.stringify(['AI-powered slide design', 'Smart templates', 'Team collaboration', 'Presentation analytics']),
    cons: JSON.stringify(['No free tier', 'Limited offline access', 'Learning curve for advanced features']),
  },
  {
    id: 'tome-ai',
    name: 'Tome AI',
    slug: 'tome-ai',
    description: 'AI-powered storytelling platform for creating interactive presentations, documents, and visual narratives',
    websiteUrl: 'https://tome.app/',
    logoUrl: '/images/tools/tome.svg',
    category: 'AI Productivity',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 8,
    pros: JSON.stringify(['AI-generated narratives', 'Interactive presentations', 'DALL-E image integration', 'Modern, clean design']),
    cons: JSON.stringify(['Limited export options', 'Free tier has watermarks', 'Less suitable for formal presentations']),
  },
  {
    id: 'motion-ai',
    name: 'Motion AI',
    slug: 'motion-ai',
    description: 'AI-powered calendar and task management that automatically schedules your day for maximum productivity',
    websiteUrl: 'https://www.usemotion.com/',
    logoUrl: '/images/tools/motion.svg',
    category: 'AI Productivity',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 19,
    pros: JSON.stringify(['AI auto-scheduling', 'Calendar and task integration', 'Team coordination', 'Priority management']),
    cons: JSON.stringify(['Expensive for individuals', 'Learning curve', 'Over-automation can feel rigid']),
  },
  {
    id: 'superhuman-email',
    name: 'Superhuman Email AI',
    slug: 'superhuman-email',
    description: 'AI-powered email client with smart replies, follow-up reminders, and productivity features for power users',
    websiteUrl: 'https://superhuman.com/',
    logoUrl: '/images/tools/superhuman.svg',
    category: 'AI Productivity',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 30,
    pros: JSON.stringify(['AI smart replies', 'Follow-up reminders', 'Keyboard shortcuts', 'Read receipts and snoozing']),
    cons: JSON.stringify(['Very expensive', 'Requires Gmail or Google Workspace', 'Overkill for casual email users']),
  },
  {
    id: 'airtable-ai',
    name: 'Airtable AI',
    slug: 'airtable-ai',
    description: 'AI-powered database and workflow platform with smart fields, automation, and team collaboration',
    websiteUrl: 'https://www.airtable.com/ai',
    logoUrl: '/images/tools/airtable.svg',
    category: 'AI Productivity',
    rating: 4.7,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 20,
    pros: JSON.stringify(['AI-powered data analysis', 'Smart fields and automation', 'Flexible database structure', 'Team collaboration']),
    cons: JSON.stringify(['AI features require paid plan', 'Can be overwhelming for beginners', 'Pricing scales with usage']),
  },
  {
    id: 'clickup-ai',
    name: 'ClickUp AI',
    slug: 'clickup-ai',
    description: 'AI-enhanced project management platform with task automation, document generation, and smart summaries',
    websiteUrl: 'https://clickup.com/ai',
    logoUrl: '/images/tools/clickup.svg',
    category: 'AI Productivity',
    rating: 4.5,
    isFeatured: true,
    pricingType: 'FREEMIUM',
    priceMonthly: 7,
    pros: JSON.stringify(['AI task generation', 'Smart document creation', 'Project summaries', 'All-in-one workspace']),
    cons: JSON.stringify(['AI features require paid plan', 'Feature overload for some', 'Learning curve for full potential']),
  },
  {
    id: 'monday-ai',
    name: 'Monday.com AI',
    slug: 'monday-ai',
    description: 'AI-powered work operating system with smart automations, insights, and workflow optimization',
    websiteUrl: 'https://monday.com/ai',
    logoUrl: '/images/tools/monday.svg',
    category: 'AI Productivity',
    rating: 4.6,
    isFeatured: true,
    pricingType: 'SUBSCRIPTION',
    priceMonthly: 10,
    pros: JSON.stringify(['AI workflow suggestions', 'Smart automations', 'Team insights', 'Visual project tracking']),
    cons: JSON.stringify(['AI requires higher-tier plans', 'Can be complex for small teams', 'Pricing per user adds up']),
  },
];

async function main() {
  console.log('Adding 50 new AI tools and reviews to database...\n');

  let added = 0;
  let updated = 0;
  let errors = 0;

  for (const tool of tools) {
    try {
      // Check if tool exists
      const existing = await prisma.tool.findFirst({
        where: {
          OR: [
            { id: tool.id },
            { slug: tool.slug },
          ],
        },
      });

      if (existing) {
        // Update existing tool
        await prisma.tool.update({
          where: { id: existing.id },
          data: {
            name: tool.name,
            description: tool.description,
            websiteUrl: tool.websiteUrl,
            logoUrl: tool.logoUrl,
            category: tool.category,
            rating: tool.rating,
            isFeatured: tool.isFeatured,
            pricingType: tool.pricingType,
            priceMonthly: tool.priceMonthly,
            pros: tool.pros,
            cons: tool.cons,
          },
        });
        updated++;
        console.log(`�?Updated: ${tool.name}`);
      } else {
        // Create new tool
        await prisma.tool.create({
          data: {
            ...tool,
          },
        });
        added++;
        console.log(`�?Added: ${tool.name}`);
      }
    } catch (error) {
      errors++;
      console.error(`�?Error for ${tool.name}:`, (error instanceof Error ? error.message : error));
    }
  }

  console.log(`\nSummary:`);
  console.log(`  Added: ${added}`);
  console.log(`  Updated: ${updated}`);
  console.log(`  Errors: ${errors}`);
  console.log(`\n�?Done! 50 AI tools with reviews have been added to the database.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
